
services:
  app:
    build: .
    container_name: swe-sixfold-container
    ports:
      - "8080:8080"  # Exposing the app on port 8080
    volumes:
      - ./app:/app  # Ensures that local app files are mapped to container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    command: python /app/app.py  # Ensure it runs app.py from the correct path

  # You can add more services if needed (e.g., database or other components)
